language: python
group: travis_latest
language: python
python:
- 2.7
- 3.6
- 3.7
- 3.8
- pypy
- pypy3
jobs:
    include:
      - python: 2.7
        env: PURE_PYTHON=1
      - python: 3.8
        env: PURE_PYTHON=1
env:
    global:
        - CC="ccache gcc"
        - CCACHE_SLOPPINESS=file_macro,time_macros,include_file_ctime,include_file_mtime
        - CCACHE_NOHASHDIR=true
        - CFLAGS="-Ofast -pipe -fomit-frame-pointer -march=native"
        - PYTHONHASHSEED=random
        - PIP_UPGRADE_STRATEGY=eager
script:
  - coverage run -m zope.testrunner --test-path=src
after_success:
  - coveralls
notifications:
  email: dev-regression-tests@nextthought.com

install:
  - pip install -U pip
  - pip install -U setuptools cython
  - pip install -U coveralls coverage
  - pip install -U -e ".[test]"


cache:
  pip: true
  directories:
    - $HOME/.ccache

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
